export enum EEnvKey {
  NODE_ENV = 'NODE_ENV',
  PORT = 'PORT',
  GLOBAL_PREFIX = 'GLOBAL_PREFIX',
  SWAGGER_PATH = 'SWAGGER_PATH',
  SECRET_JWT = 'SECRET_JWT',
  // TEAM_SERVER_NOTIFIER = 'TEAM_SERVER_NOTIFIER',
  BCRYPT_ROUND = 'BCRYPT_ROUND',
  DATABASE_HOST = 'DATABASE_HOST',
  DATABASE_PORT = 'DATABASE_PORT',
  DATABASE_USER = 'DATABASE_USER',
  DATABASE_PASSWORD = 'DATABASE_PASSWORD',
  DATABASE = 'DATABASE',
  CRAWL = 'CRAWL',
  REFRESH_TOKEN_SECRET_JWT = 'REFRESH_TOKEN_SECRET_JWT',
}

export enum ENodeEnvironment {
  DEVELOPMENT = 'development',
  PRODUCTION = 'production',
  TEST = 'test',
}
